# -*- coding: utf-8 -*-
"""CodigoEntrega2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7h7ewV1WIOVIXgLh-AbgeO5a3m6KYNb
"""

from pandas.compat.numpy.function import validate_argmax_with_skipna
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

data = pd.read_csv('https://raw.githubusercontent.com/mauriciotoro/ST0245-Eafit/master/proyecto/Datasets/calles_de_medellin_con_acoso.csv', on_bad_lines='skip',delimiter=';')

acoso = nx.from_pandas_edgelist(data, source='origin', target='destination', edge_attr='harassmentRisk')
dist = nx.from_pandas_edgelist(data, source='origin', target='destination', edge_attr='length')

start = input('Ingrese las coordenadas del inicio:')
end = input('Ingrese las coordenadas del final:')

acosoMin = nx.dijkstra_path(acoso, start,end, weight="length")
distMenor = nx.dijkstra_path(dist, start, end, weight=True)

camino = nx.DiGraph()
for i in data.iterrows():
    camino.add_edge(i[1]["origin"],
                   i[1]["destination"],
                   longitud = i[1]["length"],
                   risk=i[1]["harassmentRisk"])

def masCorto(camino, start, end, weight="length"):
    nx.draw_planar(camino.subgraph(list(distMenor)), node_color="green", font_size=8, width=0.1, with_labels=True,node_size=120)
    plt.show()

def menosAcoso(camino, start, end, weight="harassmentRisk"):
    nx.draw_planar(camino.subgraph(list (acosoMin)), node_color="green", font_size=8, width=0.1, with_labels=True, node_size=120)
    plt.show()

print("Grafo camino más corto:")
masCorto(camino, start, end, weight="length")
print("##################################################################")
print("Grafo menos Acoso:")
menosAcoso(camino, start, end, weight="harassmentRisk")