# -*- coding: utf-8 -*-
"""CodigoEntrega2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7h7ewV1WIOVIXgLh-AbgeO5a3m6KYNb
"""

pip install gmplot

from pandas.compat.numpy.function import validate_argmax_with_skipna
import pandas as pd
import gmplot
import numpy as np
import networkx as nx

data = pd.read_csv('https://raw.githubusercontent.com/mauriciotoro/ST0245-Eafit/master/proyecto/Datasets/calles_de_medellin_con_acoso.csv', on_bad_lines='skip',delimiter=';')


acoso = nx.from_pandas_edgelist(data, source='origin', target='destination', edge_attr='harassmentRisk')
dist = nx.from_pandas_edgelist(data, source='origin', target='destination', edge_attr='length')

start = input('Ingrese las coordenadas del inicio:')
end = input('Ingrese las coordenadas del final:')

acosoMin = nx.dijkstra_path(acoso, start,end, weight=True)
distMenor = nx.dijkstra_path(dist, start, end, weight=True)

print (acosoMin)
print ("---------------------------------")
print (distMenor)

#Aquí se grafica la ruta más corta
apikey = '' 
gmap = gmplot.GoogleMapPlotter(6.2476, -75.5658, 14, apikey=apikey)
distMenorZip = zip(distMenor)
gmap.polygon(*distMenorZip, edge_color='blue', edge_width=10)

gmap.draw('map.html')